spring:
  profiles:
    active: prod

  datasource:
    primary:
      hibernate:
        hbm2ddl:
          auto: validate
        dialect: org.hibernate.dialect.MySQLDialect

    secondary:
      hibernate:
        hbm2ddl:
          auto: validate
        dialect: org.hibernate.dialect.PostgreSQLDialect
        database-platform: org.hibernate.spatial.dialect.postgis.PostgisDialect
